Repository Travispersson/plaid-layout-gui, pull requests merged in 2020-12, with the labels that each got.

#22 Feature/navigation
  .gitignore
  api/src/models/__pycache__/minizinc_model.cpython-38.pyc
  api/src/utils/__pycache__/utils.cpython-38.pyc
  client/package.json
  client/src/App.js
  client/src/components/Navbar/Navbar.jsx
  client/src/components/Navbar/index.js
  client/yarn.lock
Labels: frontend

#23 experimenting with layout using styled components
  client/package.json
  client/src/App.js
  client/src/components/Navbar/Navbar.jsx
  client/yarn.lock
Labels: frontend

#24 Feature/tool component 1
  api/src/app.py
  client/src/App.js
  client/src/components/CombinationForm/CombinationForm.js
  client/src/components/CompoundForm/CompoundForm.js
  client/src/components/ConstraintForm/ConstraintForm.js
  client/src/components/ControlForm/ControlForm.js
  client/src/components/ExperimentForm/ExperimentForm.js
  client/src/components/Homepage.js
  client/src/components/PlaidForm/PlaidForm.js
Labels: flask-api, frontend

#26 Feature/represent results
  client/src/App.js
  client/src/components/Navbar/Navbar.jsx
  client/src/components/PlateLayout/ColorLegend.jsx
  client/src/components/PlateLayout/Plate.jsx
  client/src/components/PlateLayout/PlateLayout.jsx
  client/src/components/PlateLayout/Well.jsx
  client/src/components/PlateLayout/index.js
  client/src/components/PlateLayout/output_from_ex1.json
  client/src/functions/adjustColor.js
  client/src/functions/randomColor.js
Labels: frontend

#29 loader shows when waiting for data
  client/src/components/Loader/Loader.jsx
  client/src/components/Loader/index.js
  client/src/components/PlaidForm/PlaidForm.jsx
Labels: frontend

#30 Produce plate from api data
  client/public/index.html
  client/src/App.js
  client/src/components/Loader/Loader.jsx
  client/src/components/Navbar/Navbar.jsx
  client/src/components/PlaidForm/PlaidForm.jsx
  client/src/components/PlateLayout/ColorLegend.jsx
  client/src/components/PlateLayout/Plate.jsx
  client/src/components/PlateLayout/PlateLayout.jsx
  client/src/components/PlateLayout/Well.jsx
  client/src/components/PlateLayout/output_from_ex1.json
  client/src/components/Tool/Tool.jsx
  client/src/components/Tool/index.js
Labels: frontend, help wanted, important

#32 Feature/instructions
  api/plate_design/dzn_examples/pl-example20.dzn
  client/public/index.html
  client/src/App.js
  client/src/assets/img1.png
  client/src/components/Instructions/HighlightedParagraph.jsx
  client/src/components/Instructions/Instructions.jsx
  client/src/components/Instructions/index.js
  client/src/components/Navbar/Navbar.jsx
Labels: frontend

#33 Feat/highilight wells on click
  client/src/App.js
  client/src/components/PlateLayout/ColorLegend.jsx
  client/src/components/PlateLayout/Plate.jsx
  client/src/components/PlateLayout/PlateLayout.jsx
  client/src/components/PlateLayout/Well.jsx
  client/src/components/Tool/Tool.jsx
Labels: frontend

#35 Fix/color intensity
  client/src/components/PlateLayout/ColorLegend.jsx
  client/src/components/PlateLayout/Plate.jsx
  client/src/components/PlateLayout/PlateLayout.jsx
  client/src/components/PlateLayout/Well.jsx
  client/src/functions/generateHslHues.js
Labels: frontend

#36 Feature/change labels on wells
  api/plate_design/dzn_examples/pl-example11.dzn
  client/src/components/PlaidForm/PlaidForm.jsx
  client/src/components/PlateLayout/ColorLegend.jsx
  client/src/components/PlateLayout/Plate.jsx
  client/src/components/PlateLayout/PlateLayout.jsx
  client/src/components/PlateLayout/Switch.jsx
  client/src/components/PlateLayout/Well.jsx
  client/src/components/Tool/Tool.jsx
  client/src/functions/compareConcum.js
  client/src/functions/generateHslHues.js
Labels: documentation, frontend

#37 can download each result shown on plate, as a csv file
  client/package.json
  client/src/components/PlaidForm/PlaidForm.jsx
  client/src/components/PlateLayout/DownloadOuputButton.jsx
  client/src/components/PlateLayout/Plate.jsx
  client/src/components/PlateLayout/PlateLayout.jsx
  client/src/components/PlateLayout/PlateSidebar.jsx
  client/src/components/PlateLayout/Switch.jsx
  client/src/components/Tool/Tool.jsx
  client/yarn.lock
Labels: frontend
